EE_LIB_NAME = librac4ntscj.a
EE_DEFS = -DRAC4_NTSCJ=1 -DRAC_NTSCJ=1 -DNTSCJ=1 -DRAC4_V100=1 -DRAC_V100=1 -DRAC4_NTSCJ_V100=1 -DRAC_NTSCJ_V100=1

include ${CURDIR}/Makefile.defs
include $(PS2SDK)/samples/Makefile.pref
include ${CURDIR}/Makefile.eeglobal
