EE_LIB_NAME = librac4ntsck.a
EE_DEFS = -DRAC4_NTSCK=1 -DRAC_NTSCK=1 -DNTSCK=1 -DRAC4_V100=1 -DRAC_V100=1 -DRAC4_NTSCK_V100=1 -DRAC_NTSCK_V100=1

include ${CURDIR}/Makefile.defs
include $(PS2SDK)/samples/Makefile.pref
include ${CURDIR}/Makefile.eeglobal
