EE_LIB_NAME = librac4pal.a
EE_DEFS = -DRAC4_PAL=1 -DRAC_PAL=1 -DPAL=1 -DRAC4_V100=1 -DRAC_V100=1 -DRAC4_PAL_V100=1 -DRAC_PAL_V100=1

include ${CURDIR}/Makefile.defs
include $(PS2SDK)/samples/Makefile.pref
include ${CURDIR}/Makefile.eeglobal
