EE_LIB_NAME = librac4ntscu.a
EE_DEFS = -DRAC4_NTSCU=1 -DRAC_NTSCU=1 -DNTSCU=1 -DRAC4_V100=1 -DRAC_V100=1 -DRAC4_NTSCU_V100=1 -DRAC_NTSCU_V100=1

include ${CURDIR}/Makefile.defs
include $(PS2SDK)/samples/Makefile.pref
include ${CURDIR}/Makefile.eeglobal
